# Generated by Django 4.1.1 on 2022-09-25 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiTelefonos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('tel_id', models.AutoField(primary_key=True, serialize=False)),
                ('tel_nombre', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['tel_id'],
            },
        ),
        migrations.AddField(
            model_name='repuesto',
            name='rep_precio',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repuesto',
            name='rep_tip',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apiTelefonos.telefono'),
        ),
    ]
