# Generated by Django 4.1.1 on 2022-09-25 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTelefonos', '0003_rename_rep_tip_repuesto_rep_tel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repuesto',
            old_name='rep_tel_id',
            new_name='rep_tel',
        ),
    ]
