# Generated by Django 4.1.1 on 2022-09-26 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiTelefonos', '0004_rename_rep_tel_id_repuesto_rep_tel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.AutoField(primary_key=True, serialize=False)),
                ('cli_nombre', models.CharField(max_length=150)),
                ('cli_apellido', models.CharField(max_length=150)),
                ('cli_cedula', models.CharField(max_length=150)),
                ('cli_telefono', models.CharField(max_length=150)),
                ('cli_direccion', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['cli_id'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ven_id', models.AutoField(primary_key=True, serialize=False)),
                ('ven_monto', models.FloatField()),
                ('ven_cli', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apiTelefonos.cliente')),
            ],
            options={
                'ordering': ['ven_id'],
            },
        ),
    ]
