# Generated by Django 4.1.1 on 2022-09-26 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiTelefonos', '0007_venta_ven_rep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='ven_rep',
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('dven_id', models.AutoField(primary_key=True, serialize=False)),
                ('dven_rep', models.ManyToManyField(to='apiTelefonos.repuesto')),
            ],
            options={
                'ordering': ['dven_id'],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='ven_dven',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='apiTelefonos.detalleventa'),
        ),
    ]
