# Generated by Django 4.1.1 on 2022-09-26 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiTelefonos', '0008_remove_venta_ven_rep_detalleventa_venta_ven_dven'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='ven_dven',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
